Configure m-compiler-p to use --release flag when JDK > 8 is used
Otherwise, when JDK>8 is used for compilation with old-style
`target` flag (even when set to 1.8/8), incompatible change
is not resolved properly that results in:

java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.allocateBuffer(CDROutputStream_1_0.java:178)
	at com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.init(CDROutputStream_1_0.java:160)
	at com.sun.corba.ee.impl.encoding.CDROutputObject.createCDROutputStream(CDROutputObject.java:109)
	at com.sun.corba.ee.impl.encoding.CDROutputObject.<init>(CDROutputObject.java:116)
	at com.sun.corba.ee.impl.encoding.EncapsOutputStream.<init>(EncapsOutputStream.java:76)
	at com.sun.corba.ee.impl.encoding.EncapsOutputStream.<init>(EncapsOutputStream.java:68)
	at com.sun.corba.ee.impl.encoding.OutputStreamFactory$3.run(OutputStreamFactory.java:65)
	at com.sun.corba.ee.impl.encoding.OutputStreamFactory$3.run(OutputStreamFactory.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.corba.ee.impl.encoding.OutputStreamFactory.newEncapsOutputStream(OutputStreamFactory.java:61)
	at com.sun.corba.ee.impl.orb.ORBImpl.create_output_stream(ORBImpl.java:685)

when library is used with JDK8.